# multipass makes it run repeatedly on svg until it can't be squeezed smaller
multipass: true

plugins:
  - removeAttrs:
      attrs: ['path:((?!d).)*', '*:fill', '*:aria.*', '*:class.*', '*:data.*']
      # remove junk attributes
  - convertPathData:
      noSpaceAfterFlags: false
  - mergePaths:
      noSpaceAfterFlags: false
      force: true
      # force join of paths, won't work if source svgs have intersecting shapes
      # don't trust vscode svgs to be single path, so we force them into a single path
  - addAttributesToSVGElement:
      attributes:
        - fill: 'currentColor'
  - removeViewBox: true
